apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
        qix-engine: ""
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      nodeSelector:
       cloud.google.com/gke-nodepool : default-pool
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - engine
            topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 600
      containers:
      - name: engine
        image: "qlikcore/engine:12.292.0"
        resources:
            requests:
              memory: "2200Mi"
            limits:
              memory: "2200Mi"
        args: [
          "-S", "AcceptEULA=no", # change to 'yes' if you accept the Qlik Core EULA
          "-S", "LicenseServiceUrl=http://license-service:9200",
          "-S", "DocumentDirectory=/doc",
          "-S", "EnableABAC=1",
          "-S", "SystemAllowRulePath=/rules/read_engine_rules.txt"
        ]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9076
        - containerPort: 9090
        volumeMounts:
          - mountPath: /doc
            name: app-nfs
          - name: engine-prestop-hook
            mountPath: /engine-prestop-hook
          - mountPath: /rules
            name: access-control
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "/engine-prestop-hook/engine-prestop-hook.sh"]
      volumes:
        - name: engine-prestop-hook
          configMap:
            name: engine-prestop-hook
            defaultMode: 0755
        - name: app-nfs
          persistentVolumeClaim:
            claimName: nfs
        - name: access-control
          configMap:
            name: access-control
      initContainers:
        - name: volume-mount-owner
          image: "alpine:3.5"
          # Ensure the owner is nobody:nogroup
          command: ["sh", "-c", "chown -R 65534:65534 /doc"]
          volumeMounts:
            - name: app-nfs
              mountPath: /doc
      imagePullSecrets:
      - name: dockerhub
